id: PE1EA2982
initial_creation_type: ocr
source_metadata:
  volumes:
    105354ad7eeb4de3974086b37981d18d:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: སྔགས་ཀྱི་རྒྱན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1853
      volume_number: 25
