id: D0717704A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T11:07:42+00:00'
last_modified: '2022-05-26T10:57:50.176192+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    04e4:
      image_group_id: I1PD95870
      title: སྔགས་ཀྱི་རྒྱན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1853
      order: 25
      base_file: 04e4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
